service: ssrserverless

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: production
  region: ap-southeast-2

package:
  exclude:
   - src/**
   - dist/static/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
